Repository GDG-ZIMEET/ZIMEET-BackEnd-V2, pull requests merged in 2025-09, with the labels that each got.

#1 [SETTING] Project Migration
  .github/ISSUE_TEMPLATE/-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci-cd.yml
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/ZIMEET-BackEnd-V2.iml
  .idea/compiler.xml
  .idea/discord.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/gdg.z-meet.main.iml
  .idea/vcs.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  src/main/java/com/gdg/z_meet/HealthCheckController.java
  src/main/java/com/gdg/z_meet/global/config/FCMInitializer.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V10__Update_Set.sql
  src/main/resources/db/migration/V11__Update_Set.sql
  src/main/resources/db/migration/V12__Update_Set.sql
  src/main/resources/db/migration/V13__Update_Set.sql
  src/main/resources/db/migration/V14__Update_Set.sql
  src/main/resources/db/migration/V15__Update_Set.sql
  src/main/resources/db/migration/V16__Update_Set.sql
  src/main/resources/db/migration/V1__Initial_Set.sql
  src/main/resources/db/migration/V2__Update_Set.sql
  src/main/resources/db/migration/V3__Update_Set.sql
  src/main/resources/db/migration/V4__Update_Set.sql
  src/main/resources/db/migration/V5__Update_Set.sql
  src/main/resources/db/migration/V6__Update_Set.sql
  src/main/resources/db/migration/V7__Update_Set.sql
  src/main/resources/db/migration/V8__Update_Set.sql
  src/main/resources/db/migration/V9__Update_Set.sql
Labels: ⚙️ SETTING

#5 [FEATURE] WAS 다중화 및 RabbitMQ 도입
  .coderrabbit.yaml
  .github/workflows/ci-cd.yml
  build.gradle
  docker-compose.dev.yml
  docker-compose.kafka-rabbit.yml
  docker-compose.kafka-rabbitmq.yml
  docker-compose.prod.yml
  src/main/resources/application-worker.yml
  src/main/resources/application.yml
Labels: ✨ FEATURE

#8 [REFACTOR] RabbitMQ 기반 비동기 이벤트 처리 방식으로 리팩토링
  .github/workflows/ci-cd.yml
  docker-compose.dev.yml
  docker-compose.kafka-rabbitmq.yml
  docker-compose.prod.yml
  docker-compose.worker-mq.yml
  src/main/java/com/gdg/z_meet/DatabaseTest.java
  src/main/java/com/gdg/z_meet/ZiMeetApplication.java
  src/main/java/com/gdg/z_meet/domain/fcm/controller/FcmController.java
  src/main/java/com/gdg/z_meet/domain/fcm/dto/FcmBroadcastRequest.java
  src/main/java/com/gdg/z_meet/domain/fcm/dto/FcmMessageRequest.java
  src/main/java/com/gdg/z_meet/domain/fcm/dto/FcmTestRequest.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/consumer/FcmMessageConsumer.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/consumer/FcmMessageConsumerImpl.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/core/FcmMessageServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/meeting/FcmMeetingMessageServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/producer/FcmMessageProducer.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/producer/FcmMessageProducerImpl.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/profile/FcmProfileMessageServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/token/FcmTokenServiceImpl.java
  src/main/java/com/gdg/z_meet/global/config/RabbitMqConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/application-worker.yml
  src/test/java/com/gdg/z_meet/ZiMeetApplicationTests.java
  src/test/java/com/gdg/z_meet/service/FcmServiceImplTest.java
Labels: ♻️ REFACTOR

#15 [TEST] 채팅, 미팅, 프로필 알림 관련 단위 테스트 검증
  src/test/java/com/gdg/z_meet/domain/fcm/unit/config/QueryDslTestConfig.java
  src/test/java/com/gdg/z_meet/domain/fcm/unit/controller/FcmControllerTest.java
  src/test/java/com/gdg/z_meet/domain/fcm/unit/entity/TestFcmToken.java
  src/test/java/com/gdg/z_meet/domain/fcm/unit/entity/TestUser.java
  src/test/java/com/gdg/z_meet/domain/fcm/unit/repository/FcmTokenRepositoryTest.java
  src/test/java/com/gdg/z_meet/domain/fcm/unit/service/chat/FcmChatMessageServiceImplTest.java
  src/test/java/com/gdg/z_meet/domain/fcm/unit/service/consumer/FcmMessageConsumerTest.java
  src/test/java/com/gdg/z_meet/domain/fcm/unit/service/core/FcmMessageServiceImplTest.java
  src/test/java/com/gdg/z_meet/domain/fcm/unit/service/meeting/FcmMeetingMessageServiceImplTest.java
  src/test/java/com/gdg/z_meet/domain/fcm/unit/service/producer/FcmMessageProducerImplTest.java
  src/test/java/com/gdg/z_meet/domain/fcm/unit/service/profile/FcmProfileMessageServiceImplTest.java
  src/test/java/com/gdg/z_meet/domain/fcm/unit/service/token/FcmTokenServiceImplTest.java
Labels: 📔 TEST

#18 [REFACTOR] senderName, emoji 설정 로직 추가
  src/main/java/com/gdg/z_meet/domain/chat/dto/ChatMessageRes.java
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatMessageQueryService.java
Labels: ♻️ REFACTOR

#22 [FEATURE] 운영 환경 모니터링 서버 구축
  .github/workflows/ci-cd.yml
  build.gradle
  docker-compose.monitoring.yml
  docker-compose.prod.yml
  docker-compose.worker-mq.yml
  monitoring/loki/loki-config.yml
  monitoring/prometheus/prometheus.yml
  monitoring/promtail/promtail-config.yml
  src/main/resources/application.yml
Labels: ✨ FEATURE

#23 [FEATURE] 운영 환경 모니터링 로깅 레벨 추가
  monitoring/promtail/promtail-config.yml
Labels: ✨ FEATURE
